Repository op19-it-edu/base-docs, pull requests merged in 2020-01, with the labels that each got.

#21 ユースケース図の追加
  use_case.pu
Labels: reopen (by 糸井)

#28 code化したumlのディレクトリ導入
  uml.png
  uml_as_code/logical-diagram.pu
  uml_as_code/use_case.pu
Labels: レビュー待ち

#26 ER図を追加(#18)
  uml_as_code/er_diagram.pu
Labels: レビュー済（王）, レビュー済（野口）
